[features]
seeds = false
[programs.devnet]
token_contract = "HSbBGSSFedyV5LHGqqf9XkKL5ob8hTxawsSY6LG5CS69"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/amit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
